### ISSUE TITLE
很赞! 一些想法

### ISSUE THREAD

**Issue by jiexinhuang** [wuhaoworld/github-issues-blog#1]
1. 把评论直接插入到对应issue的评论区.
2. 英文版本README

我这周末会尝试一下, 如果完成会提交一个PR

赞一个~~

**Comment by wuhaoworld** [comment]
如果评论使用 github issues 的评论，获取评论还好说，提交、删除评论、回复提醒、登陆认证等功能就会大大增加程序本身的复杂度，所以我还是倾向于用第三方评论来实现此功能。

**Comment by jiexinhuang** [comment]
纯静态的页面加第三方评论的话, 相对直接用Jekyll有什么优势么?

**Comment by wuhaoworld** [comment]
Jekyll 需要本地装 ruby 环境， 每次写文章生成后才能预览到效果，或者利用 github 的自动生成功能，会有几分钟的延时，预览、修改很不方便。这套系统撰写、预览都是实时的，缺点就是 seo 不友好

**Comment by hanxi** [comment]
我觉得把 issuse 的已有评论显示出来是不错的。然后再给一个链接跳转到 issuse 的评论区。
