### ISSUE TITLE
是否允许二次开发此项目

### ISSUE THREAD

**Issue by BigCoke233** [wuhaoworld/github-issues-blog#22]
最近打算用 GitHub issues 做一个笔记本，正巧看到了您的项目，于是我拿来改了一下（当然并未完工），目前传到了我自己的仓库——[Noter](https://github.com/BigCoke233/noter)
README.md 内保留了原作者信息，并指向了这个仓库，如果您不希望我进行二次开发，请告诉我，以便我删除仓库。

**Comment by wuhaoworld** [comment]
可以的
