### ISSUE TITLE
access_token 设置完后会被自动删除

### ISSUE THREAD

**Issue by hanxi** [wuhaoworld/github-issues-blog#3]
生成 access_token 后，上传配置后就会被删除。

**Comment by hanxi** [comment]
找到解决办法了，把 access_token 拆分成两个字符串加起来。

感觉 github 被玩坏了。

**Comment by zhongwencool** [comment]
thanks~

**Comment by wuhaoworld** [comment]
应该是github 出于安全考虑做的自动过滤，已经添加说明
