### ISSUE TITLE
API的access_token注释问题

### ISSUE THREAD

**Issue by zhongwencool** [wuhaoworld/github-issues-blog#9]
1.
config.js里面的access_token:  "your_token_key";
最后写成access_taken: "your"+"token_key";
不然会像 #3 所说的那样，token上传后自动删除掉
2.
app.js的第17行：
 `per_page     : _config['per_page']`
  `// access_token : _config['access_token']`

改成：

 `// access_token : _config['access_token'] , `
` per_page     : _config['per_page']`
          
这样打开注释就可以用了，否则还要在['access_token']后加一个逗号才没有语法错～～～

**Comment by wuhaoworld** [comment]
已经修改并添加说明
